name: Sync Git Folder

concurrency: prod_environment

on:
  push:
    branches:
      # Set your base branch name here
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: 'Data'
    environment: Prod
    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}

    steps:
      - uses: actions/checkout@v3
      - uses: databricks/setup-cli@main
      - name: databricks workspace list
        run: databricks workspace list /
      - name: databricks repos create
        run: databricks repos create https://github.com/mdff-ship-it/databricks-test.git --path /Workspace/Repos/mduffy-databricks-test
      - name: databricks repos list
        run: databricks repos list
      # - name: databricks repos create
      #   run: databricks repos create https://github.com/mdff-ship-it/databricks-test.git --path /Workspace/Users/matthew.duffy@liberty-it.co.uk/mduffy-databricks-test
